import { Case } from '@/types/case';

export const mockCases: Case[] = [
  {
    id: '1',
    created_at: '2026-01-15T10:00:00Z',
    updated_at: '2026-01-15T10:00:00Z',
    owner_id: null,
    title: 'Optimización de Procesos de Exportación con IA',
    category: 'exportacion',
    summary: 'Implementación de agentes de IA para automatizar y optimizar los procesos documentales de exportación, reduciendo tiempos de tramitación en un 60%.',
    body: 'Este caso demuestra cómo la implementación de agentes de inteligencia artificial puede transformar completamente los procesos de exportación. Mediante el uso de modelos de lenguaje y automatización inteligente, logramos reducir significativamente los tiempos de procesamiento de documentación, minimizar errores humanos y mejorar la trazabilidad de los procesos.',
    status: 'published',
  },
  {
    id: '2',
    created_at: '2026-01-20T14:30:00Z',
    updated_at: '2026-01-20T14:30:00Z',
    owner_id: null,
    title: 'Sistema de Análisis de Cumplimiento Normativo',
    category: 'cumplimiento',
    summary: 'Agente de IA que monitorea y analiza cambios normativos en tiempo real, asegurando el cumplimiento continuo de regulaciones empresariales.',
    body: 'El cumplimiento normativo es un desafío constante para las empresas. Este sistema utiliza IA para monitorear cambios en la legislación, analizar su impacto en las operaciones empresariales y generar reportes automáticos de cumplimiento. La solución integra procesamiento de lenguaje natural para interpretar textos legales complejos.',
    status: 'published',
  },
  {
    id: '3',
    created_at: '2026-01-25T09:15:00Z',
    updated_at: '2026-01-25T09:15:00Z',
    owner_id: null,
    title: 'Asistente Virtual para Gestión de Cámaras de Comercio',
    category: 'camaras',
    summary: 'Chatbot inteligente que atiende consultas de asociados, gestiona trámites y proporciona información actualizada sobre servicios de la cámara.',
    body: 'Las cámaras de comercio manejan un alto volumen de consultas diarias. Este asistente virtual utiliza IA conversacional para atender a los asociados 24/7, resolver dudas sobre trámites, proporcionar información sobre eventos y servicios, y derivar casos complejos al personal humano cuando es necesario.',
    status: 'published',
  },
  {
    id: '4',
    created_at: '2026-01-28T11:45:00Z',
    updated_at: '2026-01-28T11:45:00Z',
    owner_id: null,
    title: 'Análisis Predictivo de Flujos Financieros',
    category: 'finanzas',
    summary: 'Modelo de IA que predice patrones de flujo de efectivo y optimiza decisiones de inversión empresarial.',
    body: 'La gestión financiera empresarial se beneficia enormemente del análisis predictivo. Este sistema utiliza machine learning para analizar patrones históricos, identificar tendencias y predecir flujos de efectivo futuros. Permite a las empresas tomar decisiones informadas sobre inversiones, financiamiento y gestión de capital de trabajo.',
    status: 'draft',
  },
  {
    id: '5',
    created_at: '2026-02-01T16:20:00Z',
    updated_at: '2026-02-01T16:20:00Z',
    owner_id: null,
    title: 'Optimización de Cadena de Suministro con IA',
    category: 'operaciones',
    summary: 'Sistema inteligente para predecir demanda, optimizar inventarios y coordinar logística de manera eficiente.',
    body: 'Las operaciones de cadena de suministro son complejas y dinámicas. Este sistema de IA integra datos de múltiples fuentes para predecir demanda, optimizar niveles de inventario, sugerir rutas de distribución eficientes y detectar cuellos de botella antes de que impacten las operaciones.',
    status: 'published',
  },
  {
    id: '6',
    created_at: '2026-02-03T08:00:00Z',
    updated_at: '2026-02-03T08:00:00Z',
    owner_id: null,
    title: 'Plataforma de Gobierno Corporativo Inteligente',
    category: 'gobierno',
    summary: 'Herramienta de IA para análisis de riesgos, cumplimiento de políticas y generación automática de reportes de gobernanza.',
    body: 'El gobierno corporativo requiere supervisión continua y documentación exhaustiva. Esta plataforma utiliza IA para monitorear el cumplimiento de políticas internas, identificar riesgos potenciales, generar reportes para juntas directivas y asegurar que las decisiones empresariales estén alineadas con los principios de gobernanza establecidos.',
    status: 'published',
  },
];
